# print("results", round(5/3) )
# print("results", pow(5,3))
# print("results", min(5 , 6 , 8  , 4 ) )
# print("results", max(0 ,5 ,9 ,10))
# print("results", 5**3 )
# print("results", abs(-256))
# print("results" , 5 , 45  , sep="" , end="\n")
# print("second \"  \nl\ni\nn\ne")
# input("name: ")